export const ACTIONS = {
  GET_MOVIES: "GET_MOVIES",
  ADD_MOVIE: "ADD_MOVIE",
  EDIT_MOVIE: "EDIT_MOVIE",
  DELETE_MOVIE: "DELETE_MOVIE",
  SORT_MOVIES: "SORT_MOVIES",
  FILTER_MOVIES: "FILTER_MOVIES",
  GET_MOVIE: "GET_MOVIE"
}